/*!SET MODE PostgreSQL;*/

CREATE TABLE account (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_identifier UUID NOT NULL,
    account_number VARCHAR(20) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    balance DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    date_balance_update TIMESTAMP
);

CREATE INDEX idx_user_identifier ON account (user_identifier);

CREATE INDEX idx_currency ON account (currency);

CREATE INDEX idx_status ON account (status);