/*!SET MODE PostgreSQL;*/

CREATE TABLE transaction (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_identifier UUID NOT NULL,
    account_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    transaction_date TIMESTAMP,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    type VARCHAR(20) NOT NULL,
    executed BOOLEAN,
    exchange_rate DECIMAL(10, 5),  -- Add exchange rate attribute
    FOREIGN KEY (account_id) REFERENCES account(id)
);

-- H2 Database Index Script
CREATE INDEX IF NOT EXISTS idx_account_id ON transaction(account_id);
CREATE INDEX IF NOT EXISTS idx_transaction_date ON transaction(transaction_date);
CREATE INDEX IF NOT EXISTS idx_transaction_block_identifier ON transaction(block_identifier);